version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    hostname: localhost
    ports:
      - 9092:9092
    expose:
      - 9093
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "springboot-kafka-demo:1:3"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  service1:
    image: adoptopenjdk/openjdk11-openj9
    command: 'java -jar springboot-kafka-producer/target/springboot-kafka-producer-0.0.1-SNAPSHOT.jar'
    restart: always
    volumes:
      - .:/work
    working_dir: /work
    ports:
      - 8080:8080
    depends_on:
      - kafka
  service2:
    image: adoptopenjdk/openjdk11-openj9
    command: 'java -jar springboot-kafka-consumer/target/springboot-kafka-consumer-0.0.1-SNAPSHOT.jar'
    restart: always
    volumes:
      - .:/work
    working_dir: /work
    ports:
      - 8081:8081
    depends_on:
      - kafka
